sudo: false

addons:
  apt:
    packages:
    - python-docutils

language: php
php:
  - 7.1
  - 7.2
 
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
  include:
    # test against the latest HHVM version by using trusty
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge

cache:
  directories:
    - $HOME/.composer/cache

script: ./.travis.sh

notifications:
  slack: phing:VFLtGWQdtJTgyPldJqwv5ZdH
  
