language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
matrix:
    allow_failures:
        - php: hhvm
        - php: 5.2

script: ./.travis.sh

notifications:
  hipchat: b2db23d76a46abe120c9fe87e1f63a@builds
