sudo: false

addons:
  apt:
    packages:
    - python-docutils

language: php
php:
  - 7.1
  - 7.2
  - 7.1snapshot
  - 7.2snapshot
  - master

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1snapshot
    - php: 7.2snapshot
    - php: master

cache:
  directories:
    - $HOME/.composer/cache

script: ./.travis.sh

notifications:
  slack: phing:VFLtGWQdtJTgyPldJqwv5ZdH
