sudo: false

addons:
  apt:
    packages:
    - python-docutils

language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
 
matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

script: ./.travis.sh

notifications:
  slack: phing:VFLtGWQdtJTgyPldJqwv5ZdH
  