sudo: false

addons:
  apt:
    packages:
    - python-docutils

language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - set -e
  - echo "=== SETTING GIT IDENTITY ==="
  - git config --global user.email "travis-ci-build@phing.info"
  - git config --global user.name "Phing Travis Builder"
 
matrix:
  allow_failures:
    - php: 5.2
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

script: ./.travis.sh

notifications:
  slack: phing:VFLtGWQdtJTgyPldJqwv5ZdH
  