#!/bin/sh

# NOTE FOR SETTING UP BASE JARs: 
# The saxon6.jar should be a link to the actual saxon 6.5.5 jar (in some system this exists as saxon6.jar)
# The xslthl.jar should be a link to the latest version of xslthl, for example xslthl-2.1.0.jar

BASE_JARS="/usr/share/java/saxon6.jar:/usr/share/java/xslthl.jar"

# NO CHANGES needed below this line

MAIN_CLASS=com.icl.saxon.StyleSheet
BASE_FLAGS="-Dxslthl.config=file:///usr/share/xml/docbook/stylesheet/nwalsh5/current/highlighting/xslthl-config.xml"

java -cp $BASE_JARS $BASE_FLAGS $MAIN_CLASS "$@"
