name: Phing CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v2

      - name: Test phing
        run: |
          /usr/local/bin/phpunit -v
          cd test
          ../bin/phing -debug -Dtests.codecoverage=false -listener "phing.listener.StatisticsListener"
          cd ..
