name: Phing CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer Downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      
      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v2
      - name: Test phing
        working-directory: test
        run: | 
          echo "=== SETTING GIT IDENTITY ==="
          git config --global user.email "travis-ci-build@phing.info"
          git config --global user.name "Phing Travis Builder"
          echo "=== RUN TESTS ==="
          ../bin/phing -debug -Dtests.codecoverage=false -listener "phing.listener.StatisticsListener"
